version: "3.8"
services:
  #api:
  #  build:
  #    context: .
  #    dockerfile: Dockerfile
  #  ports:
  #    - "8080:80"
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #  depends_on:
  #    - postgres
  postgres:
    container_name: eatz.postgres.db
    image: postgres:15.2
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eatz
volumes:
  pg-data:
