using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EatZ.Infra.Data.Migrations
{
    /// <inheritdoc />
    public partial class AlterOrdersTable : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("ALTER TABLE \"REVIEWS\" DROP CONSTRAINT \"FK_REVIEW_ORDER\";");
            migrationBuilder.Sql("ALTER TABLE \"ORDERS\" ALTER COLUMN \"ID\" TYPE bigint USING \"ID\"::bigint;");
            migrationBuilder.Sql("ALTER TABLE \"ORDERS\" ALTER COLUMN \"ID\" ADD GENERATED BY DEFAULT AS IDENTITY;");
            migrationBuilder.Sql("ALTER TABLE \"REVIEWS\" ALTER COLUMN \"ORDER_ID\" TYPE bigint USING \"ORDER_ID\"::bigint;");
            migrationBuilder.Sql("ALTER TABLE \"REVIEWS\" ADD CONSTRAINT \"FK_REVIEW_ORDER\" FOREIGN KEY (\"ORDER_ID\") REFERENCES \"ORDERS\" (\"ID\");");

            migrationBuilder.AddColumn<decimal>(
                name: "NET_UNIT_PRICE",
                table: "ORDERS",
                type: "numeric",
                nullable: false,
                defaultValue: 0m);

            migrationBuilder.AddColumn<int>(
                name: "QUANTITY",
                table: "ORDERS",
                type: "integer",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<decimal>(
                name: "TOTAL",
                table: "ORDERS",
                type: "numeric",
                nullable: false,
                defaultValue: 0m);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "NET_UNIT_PRICE",
                table: "ORDERS");

            migrationBuilder.DropColumn(
                name: "QUANTITY",
                table: "ORDERS");

            migrationBuilder.DropColumn(
                name: "TOTAL",
                table: "ORDERS");

            migrationBuilder.AlterColumn<string>(
                name: "ORDER_ID",
                table: "REVIEWS",
                type: "character varying(36)",
                maxLength: 36,
                nullable: false,
                oldClrType: typeof(long),
                oldType: "bigint");

            migrationBuilder.AlterColumn<string>(
                name: "ID",
                table: "ORDERS",
                type: "character varying(36)",
                maxLength: 36,
                nullable: false,
                oldClrType: typeof(long),
                oldType: "bigint")
                .OldAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
        }
    }
}
